### ISSUE TITLE
Fails on @decorators

### ISSUE THREAD

**Issue by k2snowman69** [snowcoders/sortier#108]
<img width="1206" alt="45780029-a2c0e900-bc2a-11e8-8669-b2fa41742232" src="https://user-images.githubusercontent.com/3490825/45832895-fdeced00-bcb7-11e8-89f8-33cc3c8e0eb6.png">

I don't believe there are any test cases regarding decorators yet and you can seem to stack them (though I'm unsure if order matters yet, I don't personally use them)
https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by k2snowman69** [comment]
Checking on my local machine, the latest version of sortier seems to work with decorators as expected. I've attached a sample input and output file to this comment which I derived from the screenshot above.
[typescript.decorators.input.ts.txt](https://github.com/snowcoders/sortier/files/2403706/typescript.decorators.input.ts.txt)
[typescript.decorators.output.ts.txt](https://github.com/snowcoders/sortier/files/2403707/typescript.decorators.output.ts.txt)

If the issue still persists please provide sample input and output code or files

**Comment by peterbe** [comment]
Try this file: https://gist.github.com/peterbe/8dbd6a47b7f32e63960583861246fae4
That's the one I tried before [filing this issue](https://github.com/snowcoders/sortier-vscode/issues/18).

**Comment by k2snowman69** [comment]
Got this to reproduce, thanks for the sample code! I'll look into it tonight/this weekend.

**Comment by k2snowman69** [comment]
Solved with #114 and released with 2.1.10 . Apparently flow-parser can't parse decorators by default... you have to turn it on manually. Will update sortier-vscode shortly.

**Comment by peterbe** [comment]
I can confirm that it works on VSCode now. Yay!

**Comment by k2snowman69** [comment]
Yay! Let me know if you have any feature requests or ideas where to take this in the future 😊
