### ISSUE TITLE
Usage/configuration page in docs returns 404

### ISSUE THREAD

**Issue by jpaas** [snowcoders/sortier#1490]
The https://snowcoders.github.io/sortier/#/usage/configuration page in the docs is currently a 404

**Comment by k2snowman69** [comment]
Reproduced thanks! Looks like I forgot to remove the link from the nav. This content was moved to https://snowcoders.github.io/sortier/#/options/configuration. 

I'm curious was there something in particular you were looking for that I can rewrite the docs to make easier?

**Comment by jpaas** [comment]
I just realized that you've migrated from `@snowcoders/sortier` to `sortier`, so I was just scanning the docs to see if there was anything new. I'm good. Thanks for the quick response!

**Comment by k2snowman69** [comment]
Link is now removed, thanks for the FYI!
