### ISSUE TITLE
Site docs broken

### ISSUE THREAD

**Issue by kamranayub** [snowcoders/sortier#319]
Looks like a CORS issue referencing unpkg 😢 

![image](https://user-images.githubusercontent.com/563819/52160503-eec17700-267b-11e9-859e-681c2af8df12.png)

**Comment by k2snowman69** [comment]
As mentioned in the linked task, seems to be working now. The revert of the CORS stuff will be tracked with https://github.com/snowcoders/sortier-documentation/issues/62
