### ISSUE TITLE
Flag to fail on unsorted for CI integration

### ISSUE THREAD

**Issue by TikiTDO** [snowcoders/sortier#460]
I'm currently working on setting up a new CI/CD system, and one of the checks I'd like to do is a verification that all the files are sorted.

Previously we used to rely on running `sortier` and then doing a `git diff` to check if anything changed, but our new approach doesn't mesh with that approach. I'd like to avoid having to do a manual checksum on the entire directory, so I was hoping to add a mode that just exits with an error if something is not sorted.

I could throw something together in a PR, but I'm not sure how you'd like to trigger this mode. I was thinking something like `sortier --fail-on-check [files...]`, but the current arg parsing doesn't make that very easy. Do you have any preferences?

**Comment by k2snowman69** [comment]
Sortier doesn't really "check" if things are sorted, it just sorts everything it knows how to and outputs. Sortier doesn't really track if it actually sorted something or not, it just gets input and produces output.

Most integrations I've seen from people have been using husky and lint-staged to hook into the actual git commit and having sortier run on all files being committed. There is however a [bug](https://github.com/snowcoders/sortier/issues/353) where if sortier does fail for some reason, it doesn't seem to stop the actual commit. I started looking into it and I think it has to do with the exit code but didn't get any further sadly. If this bug did get fixed, it would prevent the commit from being successful which should enforce everything being sorted in the repo.

That said, from what you described it sounds like you're running sortier across your code base then checking to see if there are any changes from within your CI itself which is interesting. Can you give more information on your CI/CD setup and usage of sortier within this scope?

**Comment by TikiTDO** [comment]
The way it works for us is we create a docker "deployment image" which contains all the resources necessary to test, lint, build, and deploy our app. This way it's super easy to reproduce the server environment for any dev, and it's possible to pick up the build from any step. However, in the interest of keeping the image small I don't want to copy the `.git` directory in there, since that would more than double the size.

This has the secondary benefit of letting us split all the various CI tasks into separate processes, and watch the exit codes of those, which works pretty well on AWS.

In this case one of the tasks is ensuring people don't commit something that's not sorted. 

One possibility would be to introduce and ENV variable (Like SORTIER_EXIT_ON_CHANGE) which could activate a piece of code that would compare the pre and post sort program text, and `process.exit(1)`. That gets around any art processing.

**Comment by k2snowman69** [comment]
Oh that makes sense, pretty cool actually! I never thought about splitting up my CI tasks but with the workflow automation stuff coming out, I can see how that can speed up your build times considerably.

Sortier right now doesn't really have CLI flags but I think this is a great use case to start. I don't have any particular preference on arg check libraries but I would take a look around to see what is out there before writing something custom that way adding new args in the future should be easy.

As far as writing the code, I think the code which will help you the most is the `formatText` function (src/index.ts). I added this so I could create a playground on the website so someone could paste input and see what the output would be via the browser. For the `--check` option you are suggesting, you could just use the formatText function and compare the input and output as you suggested. Upon mismatch result in an exit code of 1.

So yea, sounds good to me and I'd be open to it :-)

**Comment by TikiTDO** [comment]
I've used a lot of different parsing libs, but as of late I've settled on using docopt. It's platform agnostic, and it's pretty clear once you're used to their approach.

For the location code location, this would normally be called from the CLI, so I figured having it somewhere in `Reprinter.rewriteFile` and `Reprinter.rewriteText`, gated behind an option would be the simplest approach.

**Comment by k2snowman69** [comment]
CLI arguments don't really make it past `src/cli/index.ts` so I think you'll have to add a function next to Reprinter.rewriteFile (`src/reprinter/index.ts`), Reprinter.checkFile. The contents (checking the sortier ignore, etc) will be mostly the same just at the end instead of doing 
```
FileUtils.writeFileContents(filename, newFileContents);
```
You would do
```
return originalFileContents !== newFileContents
```

Then in src/cli you can do a similar sync.map but for checking the new file instead of rewriting it. I'm sure there is some really good code cleanup/deduplication after this is done such as refactoring out the sortierignore code in a shared function, etc.

**Comment by TikiTDO** [comment]
I was thinking of just adding a key to the `options` object in the CLI, and then consuming it in the rewriter. That way I could add a check to both of the existing functions without adding a new code path.

**Comment by k2snowman69** [comment]
If you add it to the options object then it would be defined in ReprinterOptions which would make it possible to add to the sortier config which considering I have isTestRun and logLevel in there would make sense.

**Comment by k2snowman69** [comment]
Just for organization, I'm assigning this to @TikiTDO but if you don't get to it just let me know :-)

**Comment by TikiTDO** [comment]
Hoping to get to it in the next week. Still finishing off the actual infrastructure that I wanted to use the feature in.

**Comment by k2snowman69** [comment]
A thought just came up about this today... What would happen if we fixed a bug in any reprinting tool (sortier, eslint, prettier, etc) but the tool wasn't run over your code base? Wouldn't all CI fail until someone manually runs the reprinting tool was on the entire code base? Wouldn't this freeze development in an unwanted way?

**Comment by TikiTDO** [comment]
This happens fairly often, and it's certainly annoying. Between having a way to turn off any test path using env and alerts getting blasted everywhere it's an occasional hiccup that's quick to fix.

**Comment by k2snowman69** [comment]
@TikiTDO Just curious if this issue is still relevant and if you'd like me to keep it open?

**Comment by k2snowman69** [comment]
Closing due to staleness
