### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [snowcoders/sortier#475]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/snowcoders/sortier/blob/master/package.json#L12

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by k2snowman69** [comment]
I thought npm added `fs@0.0.1-security` to allow declaring fs as a dependency but it just being a holding package that doesn't actually do anything.
https://www.npmjs.com/package/fs

**Comment by k2snowman69** [comment]
Just curious, is this blocking usage or install on your part? We noticed a few issues with the fs package with some other repos, just curious if it's causing issues for you as well.

**Comment by DanielRuf** [comment]
Not sure which issues you mean. It might cause confusion, issues and so on. And there are some other packages too like `path` which do contain actual code but might do something else and interfere with the internal `path` module.

**Comment by k2snowman69** [comment]
I've opened up a PR to resolve this. If you wouldn't mind taking a look that would be fantastic!
