### ISSUE TITLE
Improve search engine optimization for npms.io

### ISSUE THREAD

**Issue by Airkro** [snowcoders/sortier#516]
Original title: Why not use `sortier` as package name in npm?

**Comment by k2snowman69** [comment]
A terrible effort of self promotion :-). Really, it was originally on our internal npm repository where anything we make in house starts with `@snowcoders` to keep separate from everything else available out there. When we moved it to public domain I just didn't change it.

I'm open to changing it but not sure if it would gain anything other than a simpler npm install.

**Comment by Airkro** [comment]
Doing this maybe can improve exposure to get more support from the opensource community. (Although `sortier` is not a standard English word).

**Comment by k2snowman69** [comment]
I'm not sure renaming the package would actually achieve that (no data) but general search engine optimization of the npms.io engine isn't a terrible idea now that it's in the public space.

**Comment by k2snowman69** [comment]
If you're open to it, mind if I rename this to be `Improve search engine optimization for npms.io`? That should at least provide the data to determine what "can improve exposure to get more support from the opensource community".

**Comment by Airkro** [comment]
Just a personal opinion, it might work, it also might be a stupid idea. But do anything you want to do.

**Comment by k2snowman69** [comment]
I think it's a good idea and by having the data knowing it achieves the goal before making a switch that would be disruptive to people already using the tool will prove it's a good idea. Luckily npm's search engine is [open source](https://github.com/npms-io)!

**Comment by k2snowman69** [comment]
@Airkro Just curious, what search terms come to mind when you were looking for this package? I did some research into if renaming the package would help. Unless your package is extremely close to the specific term searched for the ranking is based on a scoring technique and keywords found in the readme and tags.

So to help improve the findability of this package, what terms come to mind when you think about this tool?

**Comment by Airkro** [comment]
I found `sortier`, based on the word `prettier`. But I quickly realized that `sortier` is not the correct spelling.
