### ISSUE TITLE
CSS sorting

### ISSUE THREAD

**Issue by k2snowman69** [snowcoders/sortier#77]
We should handle css, scss and less file types!

**Comment by k2snowman69** [comment]
Note that in css files order does matter quite considerably... so the best we could likely do is sort the properties... I'm not sure how much of a benefit there is there. If people request this then we can do it, if not, then I'll leave it.

Leaving open in case someone in the future wishes to add input.

**Comment by k2snowman69** [comment]
Branch is out!
https://github.com/snowcoders/sortier/tree/k2snowman69/css

**Comment by Airkro** [comment]
`stylelint-order` already do that. But `sortier` is a good idea too. It's difficult to choose.

**Comment by k2snowman69** [comment]
@Airkro I'll take that as a compliment :-)

As for comparing the two, I can definitely tell you that stylelint-order is far more customizable than Sortier 2.4.0. Sortier will really only care about sorting the properties within each block (at least with how I wrote the first version of css sorting; though I'm always up for new ideas). I explicitly wanted to avoid block level sorting (dom/class sorting) because it could result in several bugs since css is applied in a top down fashion. However this is something that stylelint-order does provide though I would be careful about applying that particular setting because changing the order of rules can have unexpected UI consequences. 

For Sortier, I'd say the biggest benefit really comes with the simplicity and it applying to multiple file types not just css but json, html, javascript and I'll keep adding more as time goes on. The other major thing I've tried to keep up with is making sure that blank lines are considered "context breaks" because more often than not I've seen them be used to break code into contextual groups. That said, are those context groups always exactly the same? In my personal experience, not always.

So in the end it really all depends on what your setup is, your general development flow and the level of control you want to enforce on your ordering.

I'm waiting to get a solution to https://github.com/snowcoders/sortier/issues/191 before I do the 2.4.0 release which will include css sorting. Let me know if you want me to hurry up on that; in general my goal was to release 2.4.0 before the end of the new year.

**Comment by k2snowman69** [comment]
Oh one other addition that I thought about that I plan to add for v3... In a HTML file if you have a `script` or `style` tag, the idea is we would sort the contents of that tag. That's something I don't believe stylelint would do so that's a very minor plus but a plus none the less.
