### ISSUE TITLE
Add an exclude cmd arg or configuration option.

### ISSUE THREAD

**Issue by Martaver** [snowcoders/sortier#811]
I'm working with a monorepo and I'd like to run sortier from my root against all packages.

In my repo, I use yarn workspaces to hoist node_modules under each package, so 'node_modules' exists not just in the root, but underneath each package's root directory. 

The problem is that sortier ends up running on files in each package's node_modules directory, even though it ignores the root one.

Try as I might, I can't seem to find any glob syntax for "match all except for any path containing  'node_modules'...". Thought maybe something like `yarn sortier "./packages/**/!(node_modules)/**/*.{ts,tsx,js,jsx}"` but the ** globs are just too greedy, and sortier still runs on node_modules paths.

I realised that probably this is the reason that most tools have an 'ignore' or 'exclude' option, and unfortunately sortier doesn't have it (documented at least).

I suggest adding support for and exclude configuration option, command arg and possibly even a .sortierignore file :)

**Comment by Martaver** [comment]
A second use case would be to be able to arbitrarily ignore directories that contain generated code or possibly even specs/tests, which tend to contain more obscurely structured code.

**Comment by k2snowman69** [comment]
Sorry for the delay, been slammed over the last few weeks. So we do actually support `.sortierignore`, we actually have one in the root of this project. And hilariously, the issue to add documentation for the fact we support sortierignore files has been open for quite a long time
https://github.com/snowcoders/sortier-documentation/issues/124

But yea, the feature is there, give it a whirl and see if it works for you!

**Comment by Martaver** [comment]
Hi, sorry for the wait - I'm trying to use v3.1.0 with the .sortierignore file containing glob syntax:
```
**/node_modules
```
My command is `yarn run sortier "**/*.{ts,tsx,js,jsx}"`

It seems to be running on itself (the snowcoders dir in node_modules), instead of the PWD I executed the command in...
```
Sorting node_modules/@snowcoders/sortier/dist/reprinter/index.d.ts has failed!
If this is an issue with sortier please provide an issue in Github with minimal source code to reproduce the issue
Error: Unexpected Exception - Node received is null

Sorting node_modules/@snowcoders/sortier/dist/utilities/array-utils.d.ts has failed!
If this is an issue with sortier please provide an issue in Github with minimal source code to reproduce the issue
Error: Unexpected Exception - Node received is null

Sorting node_modules/@snowcoders/sortier/dist/utilities/file-utils.d.ts has failed!
If this is an issue with sortier please provide an issue in Github with minimal source code to reproduce the issue
Error: Unexpected Exception - Node received is null

Sorting node_modules/@snowcoders/sortier/dist/utilities/log-utils.d.ts has failed!
If this is an issue with sortier please provide an issue in Github with minimal source code to reproduce the issue
Error: Unexpected Exception - Node received is null

Sorting node_modules/@snowcoders/sortier/dist/utilities/string-utils.d.ts has failed!
If this is an issue with sortier please provide an issue in Github with minimal source code to reproduce the issue
Error: Unexpected Exception - Node received is null
```

Hard to see what I might be doing wrong - is this a bug?

**Comment by k2snowman69** [comment]
That's definitely weird... I should be able to look into this tonight. Did you have a particular public repository you were running this with?

**Comment by k2snowman69** [comment]
Also do you have any settings in your `.sortierrc.js`?

**Comment by k2snowman69** [comment]
Root caused... it looks like it's picking up the .sortierignore that has been included in the publish output. I should have a fix out by the end of the day!

**Comment by k2snowman69** [comment]
Fixed in #853 and will release with 3.1.1 or higher

**Comment by k2snowman69** [comment]
Just released 3.1.1, let me know if that fixes your issue!

**Comment by k2snowman69** [comment]
Just checking in and seeing if 3.1.1 fixed the issue for you. If I don't hear back (even if it's give me a few days) I'll close out this issue after 7 days.

**Comment by Martaver** [comment]
Yeap, looks fine now, thanks very much :)
