### ISSUE TITLE
Sortier fails when sorting custom.d.ts file

### ISSUE THREAD

**Issue by GrossDesignCo** [snowcoders/sortier#873]
# Language
Typescript

# Sample input source code
```js
// custom.d.ts

declare module "*.svg" {
  const content: string;
  export default content;
}

declare module "@company/tds-*";

declare module "*.story";
```

# Expected output
None

# Actual output (or error message)
`Sorting /Users/magross/Documents/Repos/react-tds-website/src/custom.d.ts has failed!`

**Comment by k2snowman69** [comment]
PR with #877 and will release with 3.1.2 or greater
