### ISSUE TITLE
Add a way to opt-out code inline with comments (or document it if it already exists)

### ISSUE THREAD

**Issue by martaver** [snowcoders/sortier#943]
# Language
Typescript

# Sample input source code
In my other [issue](https://github.com/snowcoders/sortier/issues/942), the follow code is incorrectly messed with by sortier:
```
export interface LogFn<TScopes> {
  (key: keyof TScopes): (...args: any[]) => void;
  (...args: any[]): void;
}
```

# Expected behavior
I'd like to be able to disable sortier for this block of code. Right now the only way I know to do that is to move it to its own file and add that to `.sortierignore`.

**Comment by martaver** [comment]
Yes but then eslint/prettier wants to put it back together :D It's okay, I've got the file ignores in .sortierignore for now, it's just awkward settings a repo-level configuration for a single block in one file.

**Comment by k2snowman69** [comment]
Cool, well as long as ignoring the entire ast subtree works for you, let me think about the term and format I want to use. Thanks for the feedback!

**Comment by martaver** [comment]
No worries!

**Comment by k2snowman69** [comment]
So I've merged in a change about a week ago adding two new keywords:

 - sortier-ignore-next-line - Disables sorting on all AST nodes that start and end on the next line
 - sortier-ignore-nodes - Disables sorting on all AST nodes that start on the next line

If you get a chance, pull down the repo and give it a try. If not, just let me know and I can just publish it later and deal with the blow back if there is any.

**Comment by k2snowman69** [comment]
3.2.0
    - Added sortier-ignore-next-line support which disables sorting on all AST nodes that start and end on the next line
    - Added sortier-ignore-nodes support which disables sorting on all AST nodes that start on the next line
